# Site settings
title: Muhammad Saad Shaukat
twitter_username: saadshaukat
name: Saad Shaukat

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/saadshaukat1
 - title: LinkedIn
   url: https://www.linkedin.com/pub/saadshaukat
#Any buzzword skills you want to include
skills:
 - C/C++
 - C# 
 - Python
 - 
 - SQL
 - MATLAB
 - 

#Work experience is required
roles:
 - title: Assistant Professor
   start: 2013
   end: Ongoing
   employer: The University of Lahore Islamabad Campus
   description: 

 - title: Deputy Director Office of Research Innovation and Collaboration
   start: 2019
   end: Ongoing
   employer: Emerald Street Ventures
   description: Emerald Street Ventures was established as an incubator vehicle for the development of a number of software and legal-tech projects, and a rapidly growing, London-based start-up using innovative technologies to revolutionise and change the software and legal-tech landscape. Working with a range of cutting edge technologies and techniques including Scala, Cassandra, CoreOS, a variety of Machine Learning techniques.
 
 - title: Support Engineer
   start: 2007
   end: 2008
   employer: Viper Technlogies Pvt Ltd
   description: Covestor is an investment marketplace startup that was successfully acquired by Interactive Brokers in 2015. <br/> Working as a senior engineer, I worked closely with the CTO and across the full-stack, I was involved in all aspects of the technology including the website and back-end services.
 
 - title: Systems Specialist
   start: 2006
   end: 2007
   employer: Expert Systems Pvt Ltd
   description: Worked as a System Integration Engineer to the assemble, customizatize, configure and deploy server systems including top-of-the-line Intel Systems as Intel Blade Servers,<br/> Intel Storage Systems SSR212MA and SSR212MC2R, Network Attached Storage SS4000-E; Intel Xeon based Server Systems including S3000 and S5000. </br> Also worked on Astaro Firewalls and (nfr) IPS/IDS. Actively involved in providing technical support of the aforementioned systems at the client premises

#Education is required
education:
 - level: Masters  of Science (M.Sc.)
   date: 2013
   subject: Software Engineering
   school: University of Engineering & Technology Taxila 

 - level: Bachelor of Science (B.Sc.)
   date: 2006
   subject: Software Engineering
   school: University of Engineering & Technology Taxila 


#This section is optional (as is the image link below)

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute

#List of interesting Github repo/projects to include - optional
intro: |
  I am an engineer with 15 years experience working in technology. I have primarily worked on the JVM, but have worked across a broad range of technologies thereon: Java, Groovy, Android, Coldfusion and most recently Scala. As well as spending a reasonable amount of time building applications for the web, which has given me an exposure to a range of javascript technologies over the years, through jQuery, extjs, knockout, backbone and most recently to React. <br/><br/>
  
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
#additionalinfo: |
 #  <strong>Scala</strong>: My current role uses Scala as the primary language and have been building applications in Scala for the last two years. I am familiar with a range of Scala libraries, such as <a target="_blank" href="https://automateddeveloper.blogspot.com/2017/12/an-opinionated-guide-to-building-apis.html"> Akka-Http for building microservices</a> and <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/09/generic-programming-with-scala.html"> Shapeless for generic programming</a>, as well as familiar with a range of <a target="_blank" href="https://basementcrowd.com/2018/11/28/scala-the-aux-pattern-path-dependent-types/" >functional programming techniques available</a>.<br/><br/>
 