# Site settings
title: Muhammad Saad Shaukat
twitter_username: saadshaukat
name: Saad Shaukat

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/saadshaukat1
 - title: LinkedIn
   url: https://www.linkedin.com/pub/saadshaukat
#Any buzzword skills you want to include
skills:
 - C/C++
 - C#
 - VBA 
 - Python
 - SQL
 - MATLAB
 - 

#Work experience is required
roles:
 - title: Assistant Professor Department of Software Engineering
   start: 2013
   end: Ongoing
   employer: The University of Lahore Islamabad Campus
   description: Teach undergraduate courses Web Programming, Object-Oriented Software Engineering, 
                Computer Architecture, Software Testing and Implementation, Advanced Software Engineering, Introduction to Computing, Computer
                Programming, Management Information Systems, Multimedia Applications, Numerical Analysis and Professional Practices in Computer Science 

 - title: Deputy Director Office of Research Innovation and Collaboration
   start: 2019
   end: Ongoing
   employer: The University of Lahore Islamabad Campus
   description: Linking the University’s research community with the needs and priorities of the corporate
                sector, develop opportunities for applied research and explore opportunities for
                technology transfer and the commercialization of University research.

 - title: Deputy Director Industrial Liaison
   start: 2017
   end: Ongoing
   employer: The University of Lahore Islamabad Campus
   description: Initiate and manage engagement paradigms to facilitate faculty, alumni and Industry interactions.


 - title: Data Analyst at Quality Enhancement Cell
   start: 2013
   end: 2011
   employer: University of Engineering and Technology TAXILA
   description: Quality Assurance and Enhancement at UET TAXILA, as per standards set forth by Quality
                Assurance Agency, HEC. Conducted Academic Audit to determine faculty load and subject
                teacher ratio.
   
 - title: Founding Member, Information Management Systems Research Group
   start: 2010
   end: 2011
   employer: University of Engineering and Technology TAXILA
   description: Manage and coordinate, product-based and practically oriented research at undergraduate
                and postgraduate level.Working on the “Design and Implementation of Handheld Self-Configured Network
                Management System using Qt”
 
 - title: Support Engineer
   start: 2007
   end: 2008
   employer: Viper Technlogies Pvt Ltd
   description: Covestor is an investment marketplace startup that was successfully acquired by Interactive Brokers in 2015. <br/> Working as a senior engineer, I worked closely with the CTO and across the full-stack, I was involved in all aspects of the technology including the website and back-end services.
 
 - title: Systems Specialist
   start: 2006
   end: 2007
   employer: Expert Systems Pvt Ltd
   description: Worked as a System Integration Engineer to the assemble, customizatize, configure and deploy server systems including top-of-the-line Intel Systems as Intel Blade Servers,<br/> Intel Storage Systems SSR212MA and SSR212MC2R, Network Attached Storage SS4000-E; Intel Xeon based Server Systems including S3000 and S5000. </br> Also worked on Astaro Firewalls and (nfr) IPS/IDS. Actively involved in providing technical support of the aforementioned systems at the client premises

#Education is required
education:
 - level: Masters  of Science (M.Sc.)
   date: 2013
   subject: Software Engineering
   school: University of Engineering & Technology Taxila 

 - level: Bachelor of Science (B.Sc.)
   date: 2006
   subject: Software Engineering
   school: University of Engineering & Technology Taxila 


#This section is optional (as is the image link below)

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute

#List of interesting Github repo/projects to include - optional
intro: |
 A motivated and enthusiastic individual with an overall experience of 11 years diversified industry, academia, and administration experience. <br/><br/>
  
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: 
  <script type="text/javascript" src="https://platform.linkedin.com/badges/js/profile.js" async defer></script> 
  <div class="LI-profile-badge"  data-version="v1" data-size="medium" data-locale="en_US" data-type="vertical" data-theme="light" data-vanity="saadshaukat"><a class="LI-simple-link" href='https://pk.linkedin.com/in/saadshaukat?trk=profile-badge'>Saad Shaukat</a></div>